"""End-to-end dry run: fixture article -> rules -> fallback decision ->
slot -> publish (dry-run adapter). No network, no API key."""
from datetime import datetime, timedelta

from sqlalchemy import select

from app.models import Article, Evaluation, Post, set_setting, utcnow
from app.pipeline import publish_due, run_decisions


def make_article(session, **kw):
    defaults = dict(
        guid="e2e-1", url="https://www.tv3.lv/zinas/e2e",
        canonical_url="https://www.tv3.lv/zinas/e2e",
        title="Svarīga ziņa par notikumiem Latvijā",
        lead="Īss ievads par notikumu.", section="news",
        editor_status="must", editor_timeframe="",
        published_at=utcnow() - timedelta(minutes=30),
        images=["https://www.tv3.lv/img/x.jpg"],
    )
    defaults.update(kw)
    a = Article(**defaults)
    session.add(a)
    session.commit()
    return a


def test_must_article_gets_scheduled_and_published(session):
    article = make_article(session)
    created = run_decisions(session)
    assert created >= 1

    posts = session.execute(select(Post)).scalars().all()
    assert posts, "must article should produce posts"
    for p in posts:
        assert p.state == "scheduled"
        assert p.dry_run is True
        assert p.copy  # copy generated by fallback
        # evaluations recorded for the audit trail
    evals = session.execute(
        select(Evaluation).where(Evaluation.article_id == article.id)).scalars().all()
    assert any(e.outcome == "posted" for e in evals)

    # force due and publish via dry-run adapter
    for p in posts:
        p.scheduled_at = utcnow() - timedelta(minutes=1)
    session.commit()
    n = publish_due(session)
    assert n == len(posts)
    for p in posts:
        session.refresh(p)
        assert p.state == "published"
        assert p.platform_post_id.startswith("dry-run")


def test_can_article_skipped_without_ai(session):
    article = make_article(session, guid="e2e-2", editor_status="can",
                          url="https://tv3.lv/b", canonical_url="https://tv3.lv/b",
                          title="Pavisam parasts raksts bez steigas")
    run_decisions(session)
    posts = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert posts == []
    evals = session.execute(
        select(Evaluation).where(Evaluation.article_id == article.id,
                                 Evaluation.outcome == "ai_skip")).scalars().all()
    assert evals, "'why not posted' must have an answer"


def test_dont_article_never_decided(session):
    article = make_article(session, guid="e2e-3", editor_status="dont",
                          url="https://tv3.lv/c", canonical_url="https://tv3.lv/c")
    run_decisions(session)
    posts = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert posts == []


def test_kill_switch_holds_queue(session):
    article = make_article(session, guid="e2e-4", url="https://tv3.lv/d",
                          canonical_url="https://tv3.lv/d",
                          title="Cits unikāls virsraksts par kultūru")
    run_decisions(session)
    posts = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert posts
    for p in posts:
        p.scheduled_at = utcnow() - timedelta(minutes=1)
    set_setting(session, "kill_switch", "on")
    n = publish_due(session)
    assert n == 0
    for p in posts:
        session.refresh(p)
        assert p.state == "scheduled"  # held, not lost
    set_setting(session, "kill_switch", "")


def test_no_duplicate_posts_per_channel(session):
    article = make_article(session, guid="e2e-5", url="https://tv3.lv/e",
                          canonical_url="https://tv3.lv/e",
                          title="Vēl viens pilnīgi atšķirīgs stāsts")
    run_decisions(session)
    first = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    article.decided_at = None  # simulate re-decision (e.g. status refresh)
    session.commit()
    run_decisions(session)
    second = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert len(second) == len(first), "same article+channel must not be scheduled twice"
