"""End-to-end dry run: fixture article -> rules -> fallback decision ->
slot -> publish (dry-run adapter). No network, no API key."""
from datetime import datetime, timedelta

from sqlalchemy import select

from app.models import Article, Evaluation, Post, set_setting, utcnow
from app.pipeline import publish_due, run_decisions


def make_article(session, **kw):
    defaults = dict(
        guid="e2e-1", url="https://www.tv3.lv/zinas/e2e",
        canonical_url="https://www.tv3.lv/zinas/e2e",
        title="Svarīga ziņa par notikumiem Latvijā",
        lead="Īss ievads par notikumu.", section="news",
        editor_status="must", editor_timeframe="",
        published_at=utcnow() - timedelta(minutes=30),
        images=["https://www.tv3.lv/img/x.jpg"],
    )
    defaults.update(kw)
    a = Article(**defaults)
    session.add(a)
    session.commit()
    return a


def test_must_article_gets_scheduled_and_published(session):
    article = make_article(session)
    created = run_decisions(session)
    assert created >= 1

    posts = session.execute(select(Post)).scalars().all()
    assert posts, "must article should produce posts"
    for p in posts:
        assert p.state == "scheduled"
        assert p.dry_run is True
        assert p.copy  # copy generated by fallback
        # evaluations recorded for the audit trail
    evals = session.execute(
        select(Evaluation).where(Evaluation.article_id == article.id)).scalars().all()
    assert any(e.outcome == "posted" for e in evals)

    # force due and publish via dry-run adapter
    for p in posts:
        p.scheduled_at = utcnow() - timedelta(minutes=1)
    session.commit()
    n = publish_due(session)
    assert n == len(posts)
    for p in posts:
        session.refresh(p)
        assert p.state == "published"
        assert p.platform_post_id.startswith("dry-run")


def test_can_article_skipped_without_ai(session):
    article = make_article(session, guid="e2e-2", editor_status="can",
                          url="https://tv3.lv/b", canonical_url="https://tv3.lv/b",
                          title="Pavisam parasts raksts bez steigas")
    run_decisions(session)
    posts = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert posts == []
    evals = session.execute(
        select(Evaluation).where(Evaluation.article_id == article.id,
                                 Evaluation.outcome == "ai_skip")).scalars().all()
    assert evals, "'why not posted' must have an answer"


def test_dont_article_never_decided(session):
    article = make_article(session, guid="e2e-3", editor_status="dont",
                          url="https://tv3.lv/c", canonical_url="https://tv3.lv/c")
    run_decisions(session)
    posts = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert posts == []


def test_kill_switch_holds_queue(session):
    article = make_article(session, guid="e2e-4", url="https://tv3.lv/d",
                          canonical_url="https://tv3.lv/d",
                          title="Cits unikāls virsraksts par kultūru")
    run_decisions(session)
    posts = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert posts
    for p in posts:
        p.scheduled_at = utcnow() - timedelta(minutes=1)
    set_setting(session, "kill_switch", "on")
    n = publish_due(session)
    assert n == 0
    for p in posts:
        session.refresh(p)
        assert p.state == "scheduled"  # held, not lost
    set_setting(session, "kill_switch", "")


def test_no_duplicate_posts_per_channel(session):
    article = make_article(session, guid="e2e-5", url="https://tv3.lv/e",
                          canonical_url="https://tv3.lv/e",
                          title="Vēl viens pilnīgi atšķirīgs stāsts")
    run_decisions(session)
    first = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    article.decided_at = None  # simulate re-decision (e.g. status refresh)
    session.commit()
    run_decisions(session)
    second = session.execute(
        select(Post).where(Post.article_id == article.id)).scalars().all()
    assert len(second) == len(first), "same article+channel must not be scheduled twice"


def test_blocked_article_is_retried_then_given_up(session, monkeypatch):
    from datetime import timedelta

    from app import pipeline
    from app.models import Article, utcnow

    a = Article(guid="rt-1", url="https://tv3.lv/rt", canonical_url="https://tv3.lv/rt",
                title="T", section="news", editor_status="must", raw_json={})
    now = utcnow()

    pipeline.requeue_for_retry(a, now)
    assert a.decided_at is None                      # will be decided again
    assert a.raw_json["_decide_retries"] == 1
    assert pipeline.retry_pending(a, now)            # backoff still running
    assert not pipeline.retry_pending(a, now + timedelta(minutes=25))

    a.raw_json = {**a.raw_json, "_decide_retries": pipeline.MAX_DECISION_RETRIES}
    pipeline.requeue_for_retry(a, now)
    assert a.decided_at == now                       # gives up, stops re-deciding


def test_plan_slot_reports_the_blocking_guard(session):
    from datetime import datetime, timedelta

    from app.models import Article, Post
    from app.rules_engine import Verdict
    from app.slots import plan_slot

    a = Article(guid="rt-2", url="u", canonical_url="u", title="Virsraksts A",
                section="news")
    session.add(a)
    session.flush()
    now = datetime(2026, 8, 28, 9, 0)
    # fill the next hours so only the gap guard can block
    for i in range(20):
        session.add(Post(article_id=a.id, channel="fb_full", state="scheduled",
                         format="photo", scheduled_at=now + timedelta(minutes=10 * i)))
    session.commit()
    cfg = {"min_gap_minutes": 45, "daily_cap": 50, "quiet_hours": []}
    verdict = Verdict(outcome="eligible", reason="", earliest=now,
                      latest=now + timedelta(hours=2), allowed_windows=[])
    slot, why = plan_slot(session, "fb_full", cfg, verdict, "news", "photo",
                          "Pavisam cits virsraksts", now)
    assert slot is None or isinstance(slot, datetime)
    if slot is None:
        assert "atstarpe" in why or "daudzveidība" in why


def test_asap_ignores_ai_preferred_hour(session, monkeypatch):
    from datetime import timedelta

    from app import config as cfg_mod
    from app import pipeline
    from app.models import Article, Post, utcnow
    from sqlalchemy import select

    monkeypatch.setattr(pipeline, "decide", lambda article, verdicts, s: {
        "publish": True, "score": {"must": 0.8}, "reason": "t", "labels": [],
        "sensitivity": [],
        "channels": [{"channel": "x_tv3zinas", "format": "text_only",
                      "copy": "Teksts", "preferred_hour": 12}],
    })
    a = Article(guid="ph-1", url="https://tv3.lv/ph", canonical_url="https://tv3.lv/ph",
                title="Ātra ziņa bez attēla", section="news", editor_status="must",
                published_at=utcnow() - timedelta(minutes=5))
    session.add(a)
    session.commit()
    pipeline.run_decisions(session)
    p = session.execute(select(Post).where(Post.article_id == a.id)).scalars().first()
    assert p is not None
    # asap: iet ārā tūlīt, nevis gaida AI ieteikto 12:00
    assert p.scheduled_at - utcnow() < timedelta(minutes=30)
